### ISSUE TITLE
Exception: deck was not found: words

### ISSUE THREAD

**Issue by leej11** [psamim/kindle2anki#5]
Hey, first of all thank you for making such a cool tool! I'm excited to get using it. I've unfortunately ran into an issue when trying to run it that I can't seem to figure out what is wrong?

* I am on MacOS (M1)
* I installed anki-connect add-on
* I have Anki 2.1.44 version installed
* Anki was open in the background

```
(base) liamgower@Liams-MacBook-Pro kindle2anki % ./kindle2anki.py --vocab-db "/Users/liamgower/Documents/kindle_files/vocab.db" --deck words --no-ask --verbose
```

```
DEBUG:root:[Errno 2] No such file or directory: '/Users/liamgower/.kindle'
[0%]	 
Word: whet 
Context: Here are some more to whet your fancy: He was so happy!  
INFO:root:Adding note to words
Traceback (most recent call last):
  File "./kindle2anki.py", line 291, in <module>
    card.create(word, desc + "<br /><br />" + highlight_word_in_context(word, context))
  File "/Users/liamgower/Documents/kindle2anki/card_creator.py", line 30, in create
    self.invoke('addNote',
  File "/Users/liamgower/Documents/kindle2anki/card_creator.py", line 25, in invoke
    raise Exception(response['error'])
Exception: deck was not found: words
```

**Comment by psamim** [comment]
@leej11 Welcome!
The error says the deck `words` is not found, do you have this deck created in your Anki?
